import type { Metadata } from "next";
import "./styles.css";
import { Exo_2 } from "next/font/google";
import Header from "@/components/Header";
import Main from "@/components/Main";

const inter = Exo_2({ weight: "400", subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`grid h-screen min-h-screen grid-rows-[8rem_1fr_2rem] ${inter.className} overflow-hidden`}
      >
        <Header />
        <Main className="overflow-hidden">{children}</Main>
        <div></div>
      </body>
    </html>
  );
}
